### ISSUE TITLE
Scrypt issue while running on Windows

### ISSUE THREAD

**Issue by LogvinovLeon** [0xProject/0x-launch-kit-backend#10]
Sometimes when you try running `0x-launch-kit` on Windows you'll get an error like this:
```
Error: Cannot find module './build/Release/scrypt'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\leonidlogvinov\0x-launch-kit\node_modules\scrypt\index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

We are aware of that problem but it seems to stem from one of our dependencies, and is an issue shared across many Ethereum dev tools.

Here is the list of issues on other projects related to it that might help you resolve it:

* https://github.com/trufflesuite/ganache-cli/issues/134
* https://github.com/trufflesuite/ganache-cli/issues/151
* https://github.com/barrysteyn/node-scrypt/issues/108#issuecomment-156624724
* https://github.com/aragon/aragon-cli/issues/225
* https://github.com/embark-framework/embark/issues/509

**Comment by sudhiryadav** [comment]
change this line require("./build/Release/scrypt") to require("scrypt") from '/node_modules/scrypt/index.js'

**Comment by hichamsatoual** [comment]
> 
> 
> change this line require("./build/Release/scrypt") to require("scrypt") from '/node_modules/scrypt/index.js'

which files to edit ? explain more please

**Comment by sudhiryadav** [comment]
> > change this line require("./build/Release/scrypt") to require("scrypt") from '/node_modules/scrypt/index.js'
> 
> which files to edit ? explain more please

The file path as mentioned is inside /node_modules/scrypt folder. Edit the file index.js inside that folder. Find that line and change it accordingly.
