### ISSUE TITLE
Service crash

### ISSUE THREAD

**Issue by nOsDelAbismo** [0xProject/0x-launch-kit-backend#25]
The service crash on Debian, after minutes running 

Error: Failed to fetch parent block.
    at Object.<anonymous> (/root/0x/0x-launch-kit/node_modules/ethereumjs-blockstream/output/source/block-reconciler.js:106:27)
    at step (/root/0x/0x-launch-kit/node_modules/ethereumjs-blockstream/output/source/block-reconciler.js:32:23)
    at Object.next (/root/0x/0x-launch-kit/node_modules/ethereumjs-blockstream/output/source/block-reconciler.js:13:53)
    at fulfilled (/root/0x/0x-launch-kit/node_modules/ethereumjs-blockstream/output/source/block-reconciler.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
{ code: -32000, message: 'unknown block' }
Error: Failed to fetch parent block.
    at Object.<anonymous> (/root/0x/0x-launch-kit/node_modules/ethereumjs-blockstream/output/source/block-reconciler.js:106:27)
    at step (/root/0x/0x-launch-kit/node_modules/ethereumjs-blockstream/output/source/block-reconciler.js:32:23)
    at Object.next (/root/0x/0x-launch-kit/node_modules/ethereumjs-blockstream/output/source/block-reconciler.js:13:53)
    at fulfilled (/root/0x/0x-launch-kit/node_modules/ethereumjs-blockstream/output/source/block-reconciler.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Failed to fetch parent block.
    at Object.<anonymous> (/root/0x/0x-launch-kit/node_modules/ethereumjs-blockstream/output/source/block-reconciler.js:106:27)
    at step (/root/0x/0x-launch-kit/node_modules/ethereumjs-blockstream/output/source/block-reconciler.js:32:23)
    at Object.next (/root/0x/0x-launch-kit/node_modules/ethereumjs-blockstream/output/source/block-reconciler.js:13:53)
    at fulfilled (/root/0x/0x-launch-kit/node_modules/ethereumjs-blockstream/output/source/block-reconciler.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by nOsDelAbismo** [comment]
i solve reinstalling in a new machine from 0
