### ISSUE TITLE
Error: schema /relayerApiOrderSchema on /v2/order/:orderHash queries

### ISSUE THREAD

**Issue by laurengarcia** [0xProject/0x-launch-kit-backend#29]
Hi @dekz,

Following up on our video chat earlier... 
Pasted my console output below.
(Context: Running 0x Launch Kit locally in .ts mode and generating signed orders via CodeSandbox)

Steps to reproduce:

1/ Generate signed order (in this case, from CodeSandbox w/ Metamask)
2/ Use 0x Connect to .submitOrderAsync() to local Launch Kit Relayer
3/ Query local Launch Kit via CLI GET request, see that it returns order data properly. example:
`curl http://localhost:3000/v2/order/0xc29a9d9b797f0071b80aacf66369d866f2ddabff1a91dddbfe5fcd954158ec25`

4/ Query local Launch Kit with 0x Connect via .getOrderAsync() and get error from /relayerApiOrderSchema, example:
`client.getOrderAsync('0xc29a9d9b797f0071b80aacf66369d866f2ddabff1a91dddbfe5fcd954158ec25')`

Error:
```
client.getOrderAsync('0xc29a9d9b797f0071b80aacf66369d866f2ddabff1a91dddbfe5fcd954158ec25')
Error: Expected relayerApiOrder to conform to schema /relayerApiOrderSchema
Encountered: {
	"signature": "0x1b462e392e6008295fa29adb32d68427b7835969eca098942a585422682793f1ed67ad7f5caaa281b4852dd7e9c3acffb8fe123bb36ae62adf4cce71f9e5cef7b402",
	"senderAddress": "0x0000000000000000000000000000000000000000",
	"makerAddress": "0xb78f09d705dedaca26dc99e9ee7d789be7b38fcc",
	"takerAddress": "0x0000000000000000000000000000000000000000",
	"makerFee": "0",
	"takerFee": "0",
	"makerAssetAmount": "1000000000000000000",
	"takerAssetAmount": "10000000000000",
	"makerAssetData": "0xf47261b00000000000000000000000002002d3812f58e35f0ea1ffbf80a75a38c32175fa",
	"takerAssetData": "0xf47261b0000000000000000000000000d0a1e359811322d97991e03f863a0c30c2cf029c",
	"salt": "57718887633272621300663749607971996856877233498333220590130402684590306265495",
	"exchangeAddress": "0x35dd2932454449b14cee11a94d3674a936d5d7b2",
	"feeRecipientAddress": "0x0000000000000000000000000000000000000000",
	"expirationTimeSeconds": "1547684162302"
}
Validation errors: instance requires property "order", instance requires property "metaData"
    at Object.assert (/Users/lauren/github/0x-hackathon/node_modules/@0x/assert/lib/src/index.js:76:19)
    at Object.doesConformToSchema (/Users/lauren/github/0x-hackathon/node_modules/@0x/assert/lib/src/index.js:64:24)...

```

![image](https://user-images.githubusercontent.com/1278969/51288382-d7faff00-19b0-11e9-8f2f-1899930caa31.png)

**Comment by dekz** [comment]
Thanks @laurengarcia. I've submitted a PR #30 to fix this issue.

```
curl http://localhost:3000/v2/order/0x17a9d78d0b8951429de968d2760ecd05cf1f5093bcc6420eac6a9aa357f3844d | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   913  100   913    0     0  12670      0 --:--:-- --:--:-- --:--:-- 12680
{
  "metaData": {},
  "order": {
    "signature": "0x1cb5245d5c90a2561502d6a9f01002ac476ca51a324f3e4b26870f41ca24d3a7e54d01c59083977b92e0534642378186ee173bb33d8dbb16d03ac60fb7db962a6a02",
    "senderAddress": "0x0000000000000000000000000000000000000000",
    "makerAddress": "0x5409ed021d9299bf6814279a6a1411a7e866a631",
    "takerAddress": "0x0000000000000000000000000000000000000000",
    "makerFee": "0",
    "takerFee": "0",
    "makerAssetAmount": "100000000000000000000",
    "takerAssetAmount": "100000000000000000",
    "makerAssetData": "0xf47261b00000000000000000000000002002d3812f58e35f0ea1ffbf80a75a38c32175fa",
    "takerAssetData": "0xf47261b0000000000000000000000000d0a1e359811322d97991e03f863a0c30c2cf029c",
    "salt": "48421664369936352591469907962264571897462657488340054914166087266166526899713",
    "exchangeAddress": "0x35dd2932454449b14cee11a94d3674a936d5d7b2",
    "feeRecipientAddress": "0x0000000000000000000000000000000000000000",
    "expirationTimeSeconds": "1547623505418"
  }
}
```
